enum tokentypes{
	TEOF,TIDEN,TNUM,TASSIGN,TADD,TSUB,TMUL,TDIV,TMOD,TSEMI,TDOT,TBEGIN,TEND,TCONST,TNUMBER,TNEWLINE,
	TELSE,TIF,TINT,TRETURN,TVOID,TWHILE,TEQUAL,TNOTEQU,
	TLESS,TGREAT,TLESSE,TGREATE,TAND,TOR,TINC,TDEC,TADDASSIGN,
	TSUBASSIGN,TMULASSIGN,TDIVASSIGN,TMODASSIGN,TNOT,TERROR,
	TBRASL,TBRASR,TBRAML,TBRAMR,TBRALL,TBRALR,TCOMMA,TSEMICOLON,TRNUMBER,
	TIDENT,TOVERFLOWERR,TLONGIDERR,TSWDIGITERR,TILLSYMBOLERR
};