enum tokentypes { TEOF,TIDEN,TNUM,TASSIGN, TADD, TSEMI, TDOT, TBEGIN, TEND, TCONST, TNUMBER, TNEWLINE,
	       TELSE, TIF, TINT, TRETURN, TVOID, TWHILE, TEQUAL, TNOTEQU, TLESSE, TGREATE,
	       TAND, TOR, TINC, TDEC, TADDASSIGN, TSUBASSIGN, TMULASSIGN, TDIVASSIGN, TMODASSIGN, TERROR, TIDENT};